### ISSUE TITLE
Mongo Authentication

### ISSUE THREAD

**Issue by petems** [scobal/seyren#133]
Is there any plans to support mongo authentication? Having issues with: 

```
com.mongodb.CommandFailureException: { "serverUsed" : "localhost/127.0.0.1:27017" , "errmsg" : "need to login" , "ok" : 0.0}
```

**Comment by ngu04** [comment]
hi @petems  , I am getting similar error . Can you please let me know how to added user property on db ? Can I refer to your git hub code please ?

**Comment by petems** [comment]
@ngu04 It's been a long while and I've since switched jobs! But I think as long as the admin user has full access rights to the "seyren" db it should work.
