### ISSUE TITLE
Raise an alert if a metric has not been captured in the last N seconds or minutes

### ISSUE THREAD

**Issue by avtar** [scobal/seyren#136]
It would be great if there was a way of generating alerts when a desired metric stops being available via Graphite. The use case would be to detect when a service or host goes offline. Thoughts?

**Comment by CsabaSzabo** [comment]
+1

**Comment by yukinami** [comment]
+1

**Comment by kjenney** [comment]
+1

**Comment by pkuoExpedia** [comment]
+1
