### ISSUE TITLE
Implement http proxy option and read properties from a properties file

### ISSUE THREAD

**Issue by hvdb** [scobal/seyren#158]
Extend the seyrenconfig to make an option to provide http proxy settings.
Implement this in the notifications so that when you need a http proxy you can set it.

Also implemented an option to read the properties from the a file on the classpath.

(First time doing something on github.. sorry if there is something wrong :))

**Comment by infinitydon** [comment]
Please how do I make use of this Proxy feature? Is it available on the latest jar file?

**Comment by nedmax** [comment]
It is not working.
It should use useSystemProperties() before build() of HttpClientBuilder

**Comment by ehlerst** [comment]
I put in a merge here: https://github.com/scobal/seyren/pull/340
