### ISSUE TITLE
Alerts not running after update of seyren version

### ISSUE THREAD

**Issue by wingZero21** [scobal/seyren#186]
Hi,

Noticed that after the last update to the recent version some of the checks that were added before the update, seem to have stopped on that date.

The last check on the alerts that were setup do not seem to update unless you re-edit the settings/details on the alert and then it seems to start checking again.

EG:
Last check:
2014-04-16 12:33:09

Instead of within the last minute.

**Comment by sbasgall** [comment]
Hello,

I also have this issue. I am running seyren with a 3 server mongodb cluster.
After a day or so, seyren checks go from every minute to every hour or less.

I'm using openjdk-1.6. CPU, RAM, network traffic and disk space are all nominal.
