### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by rhythmicdevil** [scobal/seyren#196]
Hi,
I am having a problem getting an alert email to send. I dont see any errors in the log. I have tested my SMTP server from the host that the Seyren is running on and I get the test email. 

I have a test check that should be sending an alert to me but is not. I have set both the SMTP host and the SMTP port as environment vars.

 One thought I have is that the SMTP server is hosted on a different host than Seyren, would that make a difference?

Thanks for any help you can offer.

**Comment by Stalluri1** [comment]
Hey..could u please help me what did you figure out..and how did u solve your  problem

**Comment by rhythmicdevil** [comment]
Hi, I am sorry I wish I could offer some help but I dont remember what the solution was. I should have posted it here, sorry for that.

**Comment by Stalluri1** [comment]
Hey its okay , I solved the problem. I installed Seyren on an aws ec-2 instance and then installed Postfix  on the same machine which would work as sendonly mail server and then put SMTP_HOST = localhost and SMTP_PORT=25 and SMTP_FROM = alert@seyren and that worked for me.
Hope this helps someone.

**Comment by mukundparmar** [comment]
Hey first of thank you so much for above comments for help but I have problem how do you define receiver or to whom it will send an email notification. Because I coundn't figure out yet.

**Comment by Stalluri1** [comment]
go to Seyren dashboard add a check and some parameters from graphite to be checked and then you will find somewhere to "add subscription" and choose email in it and give your receiver email there. Its all in playing  with the dashboard. Hope this helps if not I can provide you with the screenshots if required.

**Comment by Stalluri1** [comment]
target is your receiving mail id. Just try with that once.

**Comment by mukundparmar** [comment]
Thank you so much I get it. and it worked.
