### ISSUE TITLE
not sending e-mails or sending once

### ISSUE THREAD

**Issue by dkatsanikakis** [scobal/seyren#203]
Hi

I have just managed to install seyren and looked fine apart from the e-mail alerting mechanism. 
I receive an e-mail  only when i first create the check and add a submission.  After the first e-mail no other e-mails arrive from the present checks.

Any ideas how to approach this?

**Comment by jaykumar2001** [comment]
Would be a nice feature, its a standard practise for any kind of notification/alerting mechanism

**Comment by scobal** [comment]
We don't have any plans to send repeated alerts at the moment. I agree it would be good though!
