### ISSUE TITLE
add influxdb metric store 

### ISSUE THREAD

**Issue by prune998** [scobal/seyren#211]

**Comment by pingw33n** [comment]
If anyone's interested I've got some rough working code with InfluxDB 0.9 and very basic Elasticsearch target checkers (simple COUNT aggregation).

![2015-07-28 15_55_56-seyren](https://cloud.githubusercontent.com/assets/758958/8931800/997f764a-3541-11e5-88df-fb4014e6b26c.png)

The graphs are iframes rendered by Grafana/Kibana.

**Comment by leelasharma** [comment]
Is there a code branch with this change somewhere?

**Comment by pingw33n** [comment]
@leelasharma yes, sorry, it's here: https://github.com/pingw33n/seyren/tree/hooter

**Comment by JulienChampseix** [comment]
I'll try it ! Thanks !

**Comment by piotr1212** [comment]
@JulienChampseix You could use https://github.com/vimeo/graphite-influxdb as bridge between seyren and influxdb for now.

**Comment by scobal** [comment]
I'm going to close this in favour of #252
