### ISSUE TITLE
"Sorry, Seyren or Graphite are not available."

### ISSUE THREAD

**Issue by magic69** [scobal/seyren#250]
Hi,

I'm trying to configure Seyren, but keep getting the same error as soon as I try to create a check:
"Sorry, Seyren or Graphite are not available.".

I can connect from CLI to the specified target host ports, in the seryren.log I mainly see it failing to connect to the seyren host /api:

 09/11/2014 13:37:26.990 [localhost-startStop-1] INFO   com.seyren.mongo.MongoStore - Done bootstrapping Mongo indexes.
 09/11/2014 13:37:27.195 [localhost-startStop-1] INFO   c.s.core.util.email.SeyrenMailSender - :@localhost
 09/11/2014 13:37:27.685 [localhost-startStop-1] INFO   c.s.c.s.l.s.PickleHandlerFactory - Carbon Pickle Listener disabled.
 09/11/2014 13:37:27.690 [localhost-startStop-1] INFO   c.s.c.s.l.s.CarbonPickleListener - Carbon Pickle Listener disabled.
 09/11/2014 13:37:27.817 [localhost-startStop-1] INFO   o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 1792 ms
 09/11/2014 13:37:33.189 [http-bio-8080-exec-5] WARN   o.j.resteasy.core.ExceptionHandler - failed to execute
 javax.ws.rs.NotFoundException: Could not find resource for full path: http://xxxx.xxxx.com:8080/api/metrics/total

Please help !
Thanks,
Ran.

**Comment by obazoud** [comment]
No comments for 2 months, closing this issue.
Feel free to open if it is still an issue.
