### ISSUE TITLE
How to alert only after a check fails for certain number of times?

### ISSUE THREAD

**Issue by sabyasachi** [scobal/seyren#254]
Most of time I would want to ignore one sudden spike or a dip. But if it is happening for quite sometime, it might be a serious issue. I could not find any interface to specify this number of consecutive cycles.

**Comment by neilprosser** [comment]
At the moment, there is no way to do that from within Seyren itself. However, a technique I've used for this kind of thing is to use a moving average. It might not be ideal for all cases, but it's possible it'll work.

We're happy to accept pull requests for this functionality though, as I think it would be extremely useful.
