### ISSUE TITLE
Lask check

### ISSUE THREAD

**Issue by PavelPolyakov** [scobal/seyren#255]
HI,

Just installed the seyren, added one target, but the "last check" parameter is not updated:
![image](https://cloud.githubusercontent.com/assets/839290/5246860/0f438b88-7976-11e4-957b-ef413d5d3089.png)

Could you clarify when should it be updated, which frequency?
What could be the reason, that the target is still not checked ? (~15 minutes has passed)

SEYREN_URL and GRAPHITE_URL are set correctly.

Regards,

**Comment by Sreshtak** [comment]
Hi
After upgrading seyren to 1.3, I'm facing the above issue. The older checks are working fine, but I'm not able to add new checks. Can you please let me know how to get rid of this issue?
