### ISSUE TITLE
Can't Run Tests

### ISSUE THREAD

**Issue by petems** [scobal/seyren#257]
```
exceptionGettingDataFromGraphiteIsHandled(com.seyren.core.util.graphite.GraphiteHttpClientTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.UnsupportedClassVersionError: org/eclipse/jetty/server/Handler : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
```

From googling, it's because the maven settings are pointing at an older java version, but OSX Yosemite requires Java Version > 1.7.0_71 because of https://bugs.openjdk.java.net/browse/JDK-8027686

I've got a change I want to make but I can't run the tests...

Any ideas?

**Comment by neilprosser** [comment]
Strange. I've just run the tests (`mvn clean verify -Pkarma`) on Yosemite using both `1.7.0_71` and `1.8.0_25` (both using Maven `3.2.5`) and they ran fine.

Is that the same command you used?

**Comment by petems** [comment]
Yeah, it's particularly an issue with the way that boxen runs java and maven it turns out. 

Closing for this: https://github.com/boxen/puppet-java/issues/51

**Comment by neilprosser** [comment]
Thanks for letting us know.
