### ISSUE TITLE
hipchat settings

### ISSUE THREAD

**Issue by chebrian** [scobal/seyren#259]
Hi, 
 i can build and use this application . i am facing a problem to setting up the notifications i like to do the settings for hipchat. 
Could you please guide me how to configure that . my doubt is how to add the room details in the below settings. 

        this.hipChatAuthToken = configOrDefault(list("HIPCHAT_AUTHTOKEN", "HIPCHAT_AUTH_TOKEN"), "my-token-number");
        this.hipChatUsername = configOrDefault(list("HIPCHAT_USERNAME", "HIPCHAT_USER_NAME"), "my-username");

**Comment by obazoud** [comment]
Hi,

Use "export" to set your hipchat settings, see https://github.com/scobal/seyren#run.

```
export GRAPHITE_URL=http://graphite.foohost.com:80
export HIPCHAT_AUTHTOKEN=xxxxxxxxxxxx
export HIPCHAT_USERNAME=xxxxxxxxxxxx
java -jar seyren-x.x.x.jar
open http://localhost:8080
```

**Comment by chebrian** [comment]
Hi, 
Thanks for the swift response. 
my clarification is in which room it will update the alert . anywhere we have to say the room name ? 

Thanks

**Comment by obazoud** [comment]
Fill "target subscription" field with rooms id (https://github.com/scobal/seyren/blob/master/seyren-core/src/main/java/com/seyren/core/service/notification/HipChatNotificationService.java#L61)

**Comment by chebrian** [comment]
Thanks . 
Testing on it . will update the status .

**Comment by chebrian** [comment]
Hi it worked. 

Thanks .
