### ISSUE TITLE
customize check  frequency time 

### ISSUE THREAD

**Issue by karthiklml** [scobal/seyren#260]
Hi, 

I am newly started to use seyren with my env.  i have 2 clarifications .

1. like to add http authentication to see the seyren console 
2. how to change the default check frequency timing. for ex : like to check every 5 min . 

Thanks .

**Comment by obazoud** [comment]
Hi,

1. Put an apache or nginx in front end with security access (http basic, LDAP, ...)
2. use GRAPHITE_REFRESH property to set your frequency

**Comment by karthiklml** [comment]
Thanks.

**Comment by somil68** [comment]
If multiple checks are there, can we set different frequency for different checks ? .It seems GRAPHITE_REFRESH is universal for all seyren checks.

**Comment by obazoud** [comment]
GRAPHITE_REFRESH is for all seyren checks.
