### ISSUE TITLE
Graphite API

### ISSUE THREAD

**Issue by DaveBlooman** [scobal/seyren#262]
Im using a odd setup with seyren, using https://github.com/vimeo/graphite-influxdb with influxDB.  When I add data a query into seyren, the graph appears in a check indicating that seyren can use the data.  However, when I add a value into warn or error, the query breaks the check.  

Any ideas to why this could be breaking?

![screenshot 2015-01-20 15 02 07](https://cloud.githubusercontent.com/assets/1492067/5819429/9d8a6d38-a0b5-11e4-95b5-6ad7bbd0ce44.png)
![screenshot 2015-01-20 15 02 57](https://cloud.githubusercontent.com/assets/1492067/5819430/9d8c7d58-a0b5-11e4-85a0-ee22d6e7a9d9.png)

**Comment by obazoud** [comment]
Seyren is compatible with Graphite Web API, not Graphite API.

**Comment by offlinehacker** [comment]
This is graphite api error, look for my pull request on graphite api for a
fix.

**Comment by DaveBlooman** [comment]
@offlinehacker I tried your fix, still getting the same issue.
