### ISSUE TITLE
Threshold base on time period

### ISSUE THREAD

**Issue by danyli78** [scobal/seyren#263]
If it's possible we can add threshold base on certain time frame? Some of my metrics have different threshold at night vs. daytime. thanks.

**Comment by felixbarny** [comment]
I think the proper way would be to implement some kind of baselining. But that is a big and complicated topic. Did you try to play around with Graphite's Holt Winters functions? http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.holtWintersAberration
