### ISSUE TITLE
Generate alert when Graphite value not matching check value ( 'equals' comparison)

### ISSUE THREAD

**Issue by jojitj** [scobal/seyren#264]
We have a healthcheck sort of Graphite metric which always stays up at value 1 as long as a process we are monitoring is available. If the process stops or dies, the Graphite values goes down to 0 or sometimes null.
Is there a way to create a Check for this with the current functionality? 
We want an ERROR alert to be generated the moment the values becomes != 1

**Comment by neilprosser** [comment]
In this situation I'd suggest having an error threshold of 0.5 and warn threshold of 0.25. You can then use Graphite's [transformNull](https://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.transformNull) function to take a null value from your target and always transform it to 0. Hopefully that should work.

**Comment by jojitj** [comment]
Thank you for the confirmation. From the code also I couldn't figure out a different way unless we have a different ValueChecker implementation.
