### ISSUE TITLE
Allow Slack channel name as target 

### ISSUE THREAD

**Issue by joelittlejohn** [scobal/seyren#266]
Finding the Slack channel id is PITA, can Seyren do this for me?

For backward compatibility, Seyren could try using the target as a channel id or as a channel name.

**Comment by joelittlejohn** [comment]
Happy to submit a PR for this, but I'm interested in your thoughts before I do.

**Comment by neilprosser** [comment]
I just tested this and it turns out it works already! With the target set to `#general` it works. I must've made a mistake (in work) when I said that didn't work.

**Comment by joelittlejohn** [comment]
:dancers:
