### ISSUE TITLE
HipChatNotificationServce still using v1

### ISSUE THREAD

**Issue by juhan88** [scobal/seyren#270]
https://github.com/scobal/seyren/blob/master/seyren-core/src/main/java/com/seyren/core/service/notification/HipChatNotificationService.java

Hipchat has deprecated v1 and, on line 89 has been updated to /v2/room/{id_or_name}/notification

Any plans to update that or make configurable?

**Comment by rposbo** [comment]
I was just about to send a PR for my fork, but it looks like it's already been patched on master!

https://github.com/rposbo/seyren/tree/hipchat-api-v2
