### ISSUE TITLE
Log Rotation

### ISSUE THREAD

**Issue by chriscannon** [scobal/seyren#274]
Is there a way to do log rotation with Seyren? I tried creating my own logrotate script, but when it runs and creates a new `seyren.log` file Seyren stops writing to it. Here's my current logrotate script:

```
/var/log/seyren/*.log {
	daily
	size 100k
	missingok
	rotate 4
	compress
	notifempty
	create 644 root root
}
```

**Comment by chriscannon** [comment]
Anyone?

**Comment by neilprosser** [comment]
Sorry, Seyren should be rotating its own logs. See [logback.xml](https://github.com/scobal/seyren/blob/master/seyren-web/src/main/resources/logback.xml#L8) for details. It should (and my installation does) rotate log files daily, keeping a maximum of 28 days.

**Comment by chriscannon** [comment]
Gotcha. Is there anyway to modify the configuration settings in that file from a command line argument to Java? Ideally I would like to have the logs rotated daily or set `<level>` to error.

**Comment by neilprosser** [comment]
There wasn't, but as of that commit I just put in there you can set the `SEYREN_LOG_FILE_LEVEL` environment variable to `error` and you'll just be logging errors.

**Comment by chriscannon** [comment]
Thanks!
