### ISSUE TITLE
Pagerduty notification not being sent for WARN

### ISSUE THREAD

**Issue by anitakrueger** [scobal/seyren#278]
I have configured pagerduty notifications for a check and alerts with ERROR level are being sent to pagerduty and create an incident.
The subscription was created with "Notify on" set to "Warn", "Error" and "OK", but for warning, no notifications are sent.
This is what I see in seyren.log:
```
 09/04/2015 13:56:29.149 [seyren.check-scheduler-1] WARN   c.s.c.s.n.PagerDutyNotificationService - Did not send notification to PagerDuty for check in state: WARN
```

I looked this up in the code and it looks like warning levels are not included in the PagerDutyNotificationService:
https://github.com/scobal/seyren/blob/master/seyren-core/src/main/java/com/seyren/core/service/notification/PagerDutyNotificationService.java#L69
https://github.com/scobal/seyren/blob/master/seyren-core/src/main/java/com/seyren/core/service/notification/PagerDutyNotificationService.java#L77
Only Error and OK are checked.

Could this be fixed or am I missing something?

Thanks
- Anita

**Comment by obazoud** [comment]
hi @anitakrueger 
Since years, it's seems that 'Warning' level was ignored by PagerDutyNotificationService :(

**Comment by obazoud** [comment]
See #284

**Comment by anitakrueger** [comment]
Hi Olivier,
Thanks a lot for the quick fix! That is awesome!
Do you build a new seyren.jar regularly or is there a release schedule?

Thanks a bunch
- Anita

**Comment by obazoud** [comment]
@anitakrueger enjoy 1.3.0 - https://github.com/scobal/seyren/releases/tag/1.3.0 !

**Comment by anitakrueger** [comment]
Wow. Thanks!

**Comment by obazoud** [comment]
@anitakrueger Feel free to reopen this issue if you have a problem with 1.3.0.
