### ISSUE TITLE
alarming off counter metrics that fire very rarely

### ISSUE THREAD

**Issue by ciaranlee** [scobal/seyren#296]
We have certain jobs that run once per day. We increment a counter in graphite when they run, and would love to be able to use Seyren to alarm if they don't complete.

If we view something like `keepLastValue(integral(stats.counts.jobs.some_rare_job))` over a 24 hour period it will be non-zero, but when I use this in a Seyren check it's value is zero because Seyren only queries over a short time period.

Is this possible to get Seyren to query graphite over a longer time period for specific metrics?

Thanks! We love Seyren and use it most days :)

**Comment by scobal** [comment]
@ciaranlee is this still an issue for you?

**Comment by ciaranlee** [comment]
Nope! Thanks :)
On Tue 3 May 2016 at 21:57, Mark Pope <notifications@github.com> wrote:

> @ciaranlee <https://github.com/ciaranlee> is this still an issue for you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scobal/seyren/issues/296#issuecomment-216662195>
>
-- 
Ciarán Lee
CTO at Intercom <http://www.intercom.io/>

@ciaran_lee <https://twitter.com/ciaran_lee>
+353.83.150.7755
