### ISSUE TITLE
SNMP Format to match RFC3416 4.2.6

### ISSUE THREAD

**Issue by nradonicich** [scobal/seyren#297]
I'm not entirely sure on the format to make a change in the code and submit it to this project, however I would like to ask for a simple change in 'seyren-core\src\main\java\com\seyren\core\service\notification\SnmpTrapNotificationService.java' Line 84 & 85 should be reversed to match RFC3416 Section 4.2.6

>The first two variable bindings in the variable binding list of an SNMPv2-Trap-PDU are sysUpTime.0 [RFC3418] and snmpTrapOID.0 [RFC3418] respectively.

from

```
            trap.add(new VariableBinding(SnmpConstants.snmpTrapOID, oid));
            trap.add(new VariableBinding(SnmpConstants.sysUpTime, new TimeTicks(5000)));
```

to

```
            trap.add(new VariableBinding(SnmpConstants.sysUpTime, new TimeTicks(5000)));
            trap.add(new VariableBinding(SnmpConstants.snmpTrapOID, oid));
```

**Comment by obazoud** [comment]
@jregovic could you help us ?

**Comment by obazoud** [comment]
#328 merged.
