### ISSUE TITLE
API documentation missing: can a check be updated via PUT?

### ISSUE THREAD

**Issue by ezeeetm** [scobal/seyren#299]
There is a section for "Update a Check" in the API docs, but there is no content in that section

https://github.com/scobal/seyren/blob/master/API.md#update-a-check

Is it correct to assume that a check can be updated via PUT, similar to how  we can update a subscription?

https://github.com/scobal/seyren/blob/master/API.md#update-a-subscription

if so, let me know and I'll add this to the API docs and do a PR

**Comment by ezeeetm** [comment]
any thoughts?

**Comment by obazoud** [comment]
Yes you can update a check with a PUT.
https://github.com/scobal/seyren/blob/master/seyren-api/src/main/java/com/seyren/api/jaxrs/ChecksResource.java#L79

**Comment by obazoud** [comment]
Without answer, I am closing this issue.
Feel free to re-open if it is still an issue.
