### ISSUE TITLE
HipChat Behind The Proxy

### ISSUE THREAD

**Issue by infinitydon** [scobal/seyren#302]
Hi,

My server is sitting behind a proxy, How can I set Seyren to use the proxy server to relay Hipchat messages?

I have tried the following procedure:

java -DproxySet=true -DproxyHost=10.xx.xx.xx -DproxyPort=31128 -jar /root/seyren/seyren-1.3.0.jar -httpPort=8081

But still not working, Hipchat is still trying to connect directly but the network keeps dropping the request because all web requests should come from the proxy server. Below is the error from the logs:

19/05/2015 17:24:00.625 [http-bio-8081-exec-3] WARN   c.s.c.s.n.HipChatNotificationService - Error posting to HipChat
 org.apache.http.conn.HttpHostConnectException: Connect to api.hipchat.com:443 [api.hipchat.com/54.235.88.28] failed: Connection refused

**Comment by obazoud** [comment]
IMHO should be "http.proxyHost" and "http.proxyPort".
