### ISSUE TITLE
Add versioning for check configuration

### ISSUE THREAD

**Issue by jbethun2** [scobal/seyren#305]
I’d like to version the configuration of monitored metrics, such that we can revert to a previous state when someone misconfigures alerting, threshold, or metric settings.  This could integrate with Access Controls to track which users make changes. The same goals would also be met by integrating with a Git repository for configuration storage.

**Comment by scobal** [comment]
Thanks @jbethun2. Your best bet here if you'd still like to do this is to build some kind of workflow outside Seyren using the API:

https://github.com/scobal/seyren/blob/master/API.md
