### ISSUE TITLE
Order checks in the same state by title

### ISSUE THREAD

**Issue by robinjmurphy** [scobal/seyren#316]
I'd like to order checks that have the same state on the main page by their name, after the state. I think this will be a similar change to #108 but with an array passed to [orderBy] (https://docs.angularjs.org/api/ng/filter/orderBy) and title used as a secondary sort.

I'm having a little trouble getting dependencies installed currently but happy to do the work if you think it sounds like a reasonable thing to do?

**Comment by scobal** [comment]
Included with 927a2e8, thanks.
