### ISSUE TITLE
Parsing Seyren Data ( Integration with another RMM system)

### ISSUE THREAD

**Issue by dheerajpanyam** [scobal/seyren#320]
Hi ,

 I need to parse the alerts from Seyren output to integrate the alerts with our alerting system which has a REST API available for doing this. I am not able to get to the  HTTP POST subscription data at all, it is not recognising it , i don't know what form fields internally Seyren uses , I wrote a little python socketserver which is a SimpleHTTPServer implementation and using CgiFieldStorage, below is my code I would like to retrieve data from the form which is a CgiFieldStorageInstance, ( shown below) would like to get all the alerts.

Thanks in advance and appreciate your help

Regards
Dheeraj

class ServerHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):

def do_GET(self):
    logging.warning("======= GET STARTED =======")
    logging.warning(self.headers)
    SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)

def do_POST(self):
    logging.warning("======= POST STARTED =======")
    logging.warning(self.headers)
    form = cgi.FieldStorage(
        fp=self.rfile,
        headers=self.headers,
        environ={'REQUEST_METHOD':'POST',
                 'CONTENT_TYPE':self.headers['Content-Type'],
                 })
    logging.warning("======= POST VALUES =======")
    logging.warning(form)
    logging.warning("\n")
    SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)
Handler = ServerHandler

httpd = SocketServer.TCPServer(("", PORT), Handler)

**Comment by scobal** [comment]
If you're still working on this then perhaps you could try our API:

https://github.com/scobal/seyren/blob/master/API.md
