### ISSUE TITLE
How does HTTP Subscription  work?

### ISSUE THREAD

**Issue by dheerajpanyam** [scobal/seyren#323]
When i choose HTTP subscription type , Seyren POSTS data to a URL is what i understand from the git documentation. Is it some kind of  "form" POST and seyren hides the form fields. I am trying to write a python adapter but i do not know the field names to retrieve the alerts if i have to use the FieldStorage  instance, please help?

Regards
Dheeraj

**Comment by alenkacz** [comment]
Actually the HTTP subscription just serializes into JSON information about the check and alert that triggered it. Example of such json

	{
	  "alerts": [
		{
		  "id": null,
		  "checkId": null,
		  "value": 12,
		  "target": "the.target.name",
		  "warn": 5,
		  "error": 10,
		  "fromType": "WARN",
		  "toType": "ERROR",
		  "timestamp": null
		}
	  ],
	  "preview": "<br /><img src=http://localhost:64594/graphite/render/?target=statsd.metric.name&from=18:59_20160218&until=17:59_20160218&target=alias(dashed(color(constantLine(1),%22yellow%22)),%22warn%20level%22)&target=alias(dashed(color(constantLine(10),%22red%22)),%22error%20level%22)&width=500&height=225></img>",
	  "seyrenUrl": "http://localhost:64594/seyren",
	  "check": {
		"id": null,
		"name": "check-name",
		"description": null,
		"target": "statsd.metric.name",
		"from": null,
		"until": null,
		"warn": "1",
		"error": "10",
		"enabled": true,
		"live": false,
		"allowNoData": false,
		"state": "ERROR",
		"lastCheck": null,
		"subscriptions": []
	  },
	  "subscription": {
		"id": null,
		"target": "http://localhost:64594/myendpoint/thatdoesstuff",
		"type": "HTTP",
		"su": false,
		"mo": false,
		"tu": false,
		"we": false,
		"th": false,
		"fr": false,
		"sa": false,
		"ignoreWarn": false,
		"ignoreError": false,
		"ignoreOk": false,
		"fromTime": null,
		"toTime": null,
		"enabled": false
	  }
	}

Hope it helps.
