### ISSUE TITLE
Is it possible to bookmark filtered list of checks?

### ISSUE THREAD

**Issue by payman81** [scobal/seyren#324]
In order to find related checks, I always have to filter them. I was wondering if it was possible to bookmark filtered list of checks.
Thanks.

**Comment by ipaponov** [comment]
In order to do that, you need to teach check search box to understand request params.
Here is a simple trick how to do that
https://github.com/ipaponov/seyren/commit/e84798e0d41a492b2537e4347300d83afb095269
