### ISSUE TITLE
Is it possible to "debounce" an alert?

### ISSUE THREAD

**Issue by rsetzer** [scobal/seyren#329]
I have a scenario where an application processes orders (an order file) through 3 distinct stages; received (order file parsed), ingested (written to database) and submitted (given to manufacturing). I have created checks to gate these stages looking at the diff between received and ingested and again at the diff between ingested and submitted. If they differ an email is sent to the appropriate party to investigate.

The problem arrises when a delay exists between the ingested metric push and the submitted metric push, which is sometimes lengthy but usually 5 minutes or so. Before the submitted metric finds its way to Graphite, an error alert email is fired (change to ingested metric is detected), then say 5m later the OK alert fires. This is ok, but I really would like a way to insert a delay and retest prior to sending an alert at all.

I saw something related where the suggestion was to use a MovingAverage which I experimented with to no avail.

I am using the following expression in the alert:

diffSeries(sumSeries(transformNull(sfly.*.sbs.kpis.uhg_anoc.*.orders_ingested.count)), sumSeries(transformNull(sfly.*.sbs.kpis.uhg_anoc.*.orders_submitted.count)))

The intent is to alert when the ingested series count is larger than the submitted series count.

Note, We are not pushing metrics at a regular interval i.e., 1/sec. Orders arrive as a collection in an order file at random times (< 50 datpoints/day) and the metrics are pushed accordingly which also lessens the load on an already busy Graphite Server.

Any help is greatly appreciated.

Thanks,
Ron

**Comment by scobal** [comment]
@rsetzer let me know if you managed to find a solution to this or if you're still looking for help

**Comment by rsetzer** [comment]
I am guessing that someone here might still have some interest, I am no longer involved with said project. I will forward to the appropriate person.

Thanks,
Ron S.
