### ISSUE TITLE
Karma - Integration tests

### ISSUE THREAD

**Issue by nspragg** [scobal/seyren#334]
The integration tests are failing due to a breaking change in Karma 0.13.x

Error:
PhantomJS 1.9.8 (Linux 0.0.0) ERROR 
  You need to include some adapter that implements __karma__.start method! 

See breaking changes in 0.13.0:
https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#breaking-changes

**Comment by scobal** [comment]
These were fixed somewhere along the line: https://travis-ci.org/scobal/seyren
