### ISSUE TITLE
Please provide more explanation about "from" and "until" in checks

### ISSUE THREAD

**Issue by giridhara** [scobal/seyren#336]
Hi,

Seyren is so easy to setup and use. Thank you!

I want to know more about "from" and "until" fields while we are adding new 'check'

Thanks,
Giridhar.

**Comment by shingjay** [comment]
The 'from' and 'until' fields are used as params to hit Graphite.. You can specify -1minutes/days, etc.

**Comment by obazoud** [comment]
See [Documentation](http://graphite.readthedocs.org/en/1.0/url-api.html#from-until)
