### ISSUE TITLE
WARN level doesn't send SMS

### ISSUE THREAD

**Issue by inteloid** [scobal/seyren#341]
Hi,

I don't receive SMS message when status switches to WARN. Email notification works fine for that case though.

**Comment by alenkacz** [comment]
Actually this seems to be a feature - I checked the code and it really sends SMS just for error and ok.

My proposed solution would be - allow to send sms for warn level but leave it as optional (add another field to the configuration that will say whether warn sms notifications are wanted). Or we can skip the settings part - it was just for "backwards" compatibility if the current state is actually desired for most of the users.

So this is probably question for @obazoud - I am happy to implement it if we agree on the solution
