### ISSUE TITLE
Problem accessing Graphite server

### ISSUE THREAD

**Issue by cmdel** [scobal/seyren#345]
I've set up the Docker container and Seyren loads up just fine, but I can't get any metrics from Graphite. Is there an issue that it's on HTTPS?
the URL I'm providing is https://servername
with no ports at the end.
Is there a debug log somewhere to take a look where it's failing?
Thanks,

**Comment by cmdel** [comment]
Anyone has any thoughts on this?

Thanks.

**Comment by obazoud** [comment]
Graphite is available on http://localhost:8081/ with Basic Auth guest/guest.
I will update documentation.

**Comment by cmdel** [comment]
I see. So what if I want to point it to an existing Graphite server? Is there a config file I can define this?

**Comment by obazoud** [comment]
You have to change docker-compose file.

**Comment by cmdel** [comment]
Thanks! I'll try it out.
