### ISSUE TITLE
Add alert on changing to "UNKNOWN" state

### ISSUE THREAD

**Issue by yakovkeselman** [scobal/seyren#349]
Not sure if this has been requested and/or addressed already: it would be great to have the ability to alert on changing the state to "UNKNOWN". In my simulation, it indicates a failure in graphite or its environment (e.g., the VM is down). Seyren would provide a very valuable alert in this case. I'll be happy to try my hand at implementing this functionality if it has not been done already.

Thanks for the very nice alerting mechanism!

Yakov

**Comment by scobal** [comment]
This should be covered as part of #136
