### ISSUE TITLE
Receives data from Graphite but doesn't send emails.

### ISSUE THREAD

**Issue by lepiklepik** [scobal/seyren#352]
Hey,

I have the following issue.
Seyren receives data from Graphite, generates alers but doesn't send emails.
State of the check record is always 'Unknown'.
However, when I click on remove all alerts - it sends single email.
Both Seyren and Graphite are located on the same host.
SMTP: Mandrill
Linux distro: Debian 7
![seyren123](https://cloud.githubusercontent.com/assets/8902584/11297412/dcf04ba4-8f80-11e5-94b1-de57af8e8b57.png)

Thanks for this great piece of software.

**Comment by scobal** [comment]
Thanks for the bug report. Did you get this working? If not could you send over any logs you have from Seyren please?
