### ISSUE TITLE
How detect that there is no data during 10 minutes 

### ISSUE THREAD

**Issue by rubenpapovyan** [scobal/seyren#353]
Hi,
Is there any way to detect that in graphite there is no data for 10 minutes (I need to be notified in that case ).
It will be very nice if you provide instruction for seyren.

Thanks in advance.

**Comment by slogar** [comment]
Hi, 

you probably figure it out already but anyway you can create a new alarm with following formula transformNull(keepLastValue(dataserie, 10),1000). As alarm you setup if it's above 999 than you don't have data for 10 minutes (data points). Hope that helps.
