### ISSUE TITLE
not able to start Seyren ndex not found with name [checkId_1_target_1]

### ISSUE THREAD

**Issue by alseddnm** [scobal/seyren#354]
Hello, I would like to run/debug Seyren locally and am hitting this issue -> basically it tries to drop mongodb index which doesn't exist -> MongoStore.java line# 105

Please correct the problem by removing the clash. If it's something else, please let us know on Github!
 com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "nIndexesWas" : 3 , "ok" : 0.0 , "errmsg" : "index not found with name [checkId_1_target_1]" , "code" : 27}
	at com.mongodb.CommandResult.getException(CommandResult.java:76) ~[mongo-java-driver-2.12.4.jar:na]

Thank you...!

**Comment by kierangirvan** [comment]
I'm also experiencing the same problem.

**Comment by KaiPierre** [comment]
Same bug here

**Comment by kierangirvan** [comment]
Thanks @KaiPierre, Seyren now starts having installed Mongodb v3.0.

**Comment by AeroNotix** [comment]
Same issue here.  Running seyren-1.3.0 and mongo 3.2.3.

**Comment by scobal** [comment]
Just to let you know I've just updated the Mongo version to 3.2.2, 988f3de. It will be included in the next release, thanks!

**Comment by deniszh** [comment]
Just faced same issue on MacOS X. Tried master and 1.5.0 release.
```web_1       | Caused by: com.mongodb.MongoCommandException: Command failed with error -1: 'index not found with name [checkId_1_target_1]' on server mongodb:27017. The full response is { "nIndexesWas" : 3, "ok" : 0.0, "errmsg" : "index not found with name [checkId_1_target_1]" }```
