### ISSUE TITLE
Setting configuration via a config file?

### ISSUE THREAD

**Issue by jregovic** [scobal/seyren#355]
Is there a config file that I can create rather than having to set environment variables prior to starting seyren?

**Comment by MartinNowak** [comment]
Just put something like this in a file, e.g. `/etc/default/seyren` and source it using `[ -f /etc/default/seyren ] && source /etc/default/seyren` in your bash console or init script.
```
export GRAPHITE_HOST=http://example.com
export SMTP_HOST=mail.example.com
```

**Comment by scobal** [comment]
Thanks @MartinNowak!

We really should support a nicer config format though, maybe one for the future
