### ISSUE TITLE
mongo 3.2 incompatibility

### ISSUE THREAD

**Issue by jeffastorey** [scobal/seyren#356]
When first starting up seyren, I got this error

    Dec 21, 2015 10:50:00 AM com.mongodb.ServerMonitor$ServerMonitorRunnable run
    WARNING: Exception in monitor thread during notification of server state change
    java.lang.NoClassDefFoundError: com/mongodb/ChangeEvent
    at com.mongodb.ServerMonitor$ServerMonitorRunnable.sendStateChangedEvent(ServerMonitor.java:135)
	at com.mongodb.ServerMonitor$ServerMonitorRunnable.run(ServerMonitor.java:118)
	at java.lang.Thread.run(Thread.java:745)

Adding a mongo java driver to the classpath fixed the issue. Is this expected? If so, it should be documented.

**Comment by jeffastorey** [comment]
It looks like this is actually an issue with mongo 3+

I tried updating my local copy of mongo driver to 2.14.0 to work with mongo 3, but that causes differnet errors with removing existing indices during the bootstrap process. A code 27 was thrown and not the "-5" the existing seyren code looks for.

**Comment by jeffastorey** [comment]
When testing with the mongo 3.2 drivers, I found that the seyren code breaks because the driver code is different and is not backwards compatible. I immediately found that CommandFailureException is no longer a class in the mongo 3.2 driver and caused exceptions in the seyren code.

**Comment by scobal** [comment]
Just to let you know I've just updated the Mongo version to 3.2.2,  988f3de. It will be included in the next release, thanks!
