### ISSUE TITLE
Startup very slow

### ISSUE THREAD

**Issue by rolanddb** [scobal/seyren#364]
Hi,
I've noticed sometimes that it takes a really long time for Seyren to start up. In a recent case, 3 minutes before the UI is accessible. See these timestamps:

```
Jan 29, 2016 4:01:54 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Jan 29, 2016 4:04:51 AM org.apache.catalina.util.SessionIdGenerator createSecureRandom
INFO: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [174,801] milliseconds.
```
I'm running Seyren on a Digital Ocean VM with 2GB ram and SSD drive. Nothing else runs on the machine. Any idea how this can be resolved?

**Comment by scobal** [comment]
This might help, looks to be a Tomcat/JVM thing

https://wiki.apache.org/tomcat/HowTo/FasterStartUp#Entropy_Source
