### ISSUE TITLE
Alerting based on a variance instead of a set threshold?

### ISSUE THREAD

**Issue by calebcall** [scobal/seyren#365]
It would be nice if seyren could be configured to alert based on a variance.  For example, I'd like to know if a certain metric is 10% higher (or lower) than it has been over the last day (or whatever timeframe).  The reason a set threshold might not fit is the number is expected to grow so it will always cross a static threshold at a given time.  Or maybe  that same metric, that's expected to grow over time and never shrink, suddenly shrinks.  A static threshold would't catch this, but a variance would.

**Comment by sjernigan** [comment]
Check out the following functions and I think you'll find a combination that works: derivative, diff and timeShift, holtWinters.
