### ISSUE TITLE
Trigger by "Less Than"

### ISSUE THREAD

**Issue by 1337newbee** [scobal/seyren#368]
Currently, all the alerts are triggered by "Bigger Than", say if I have a metrics as "memory free"
I wanted the warning when memory free is less than 10% and an error when it's less than 5%.

I can use 1-memory-used to calculate memory available, but it will be better if we have that feature supported as well.

**Comment by scobal** [comment]
Hi Tracy,

Does setting the error threshold lower than warning threshold give you what you want here? 

Mark

**Comment by newbeetracy** [comment]
I don't think so. we still want to keep the warning as lower than error. but different ways of trigger it.
Instead of memory-used > 90%
I'd like memory-available < 10% to trigger the alert

**Comment by scobal** [comment]
Hmm perhaps I'm missing something. Am I right in thinking you have a metric like:

server.memory-available

And the value can be something like a range of 0..4000 to indicate megabytes available?

**Comment by newbeetracy** [comment]
well, my metrics are from Graphite, so I have all of the memory metrics
memory-used
memory-free
memory-cached
memory-buffered

To get memory available, I will add memory-free+memory-buffered+memory-cached, plus, they will be all in percentage (by dividing the memory_total), so range would be 0-100

**Comment by scobal** [comment]
OK great :-)

So you'd like Seyren to warn when the value is between 10-5 and to error when the value is below 5?

**Comment by 1337newbee** [comment]
Exactly

**Comment by scobal** [comment]
Cool. So unless I'm still missing something, it sounds like you need to set the warn threshold to 10 and the error threshold to 5.

**Comment by 1337newbee** [comment]
it sounds right. Just how the threshold will be triggered. If I put the current values into seyren, it will trigger
the alert when my memory_available larger than 19 and trigger error when memory_available bigger than 5.

But in the real case, we want alert triggered if memory_available is less than 10

**Comment by scobal** [comment]
Have you tried setting the warn threshold to 10 and the error threshold to 5? Seyren will handle what you're describing automatically.

**Comment by scobal** [comment]
@1337newbee let me know if you managed to get this working please

**Comment by 1337newbee** [comment]
It worked very well for me. Thanks.
Just wondering, if the bigger than (and smaller than ) case also includes "equal".
For instance, if the metric is smaller/equal than the threshold, seyren alert will be triggered?

**Comment by scobal** [comment]
@1337newbee not sure off the top of my head but please let me know if you find out!
