### ISSUE TITLE
No pictures in checks

### ISSUE THREAD

**Issue by kskaran94** [scobal/seyren#372]
Pictures are not loaded in create checks

**Comment by alenkacz** [comment]
Can you be more specific? Pictures work for me...

**Comment by kskaran94** [comment]
They pictures don't load and i think i am not able to connect to graphite. Can you help me on this?

**Comment by alenkacz** [comment]
And how are you configuring your graphite url? is there something in seyren log?

**Comment by kskaran94** [comment]
I am using the Environment variable. My graphite is running on port 81, so specified that as well. Removed the authentication for testing seyren.

**Comment by scobal** [comment]
@kskaran94 please re-open and attach any logs you have from Seyren if you're still seeing this issue, thanks!
