### ISSUE TITLE
Seyren Proxy Settings - Not Working

### ISSUE THREAD

**Issue by phateuk** [scobal/seyren#383]
Having a major issue getting Seyren to communicate with slack.com using the proxy settings. My Graphite/Grafana server is sat behind our corporate firewall and the IP address of slack.com keeps changing as they don't have a static address on AWS.

I've tried the seyren v1.3.0 JAR running with the java cli and also now using the .war file within a tomcat 7 setup and it's still attempting to communicate directly rather than via a proxy. The settings I'm using in my tomcat init script are:

JAVA_OPTS='-server -Dhttps.proxyHost=IP -Dhttps.proxyPort=3128 -Dhttp.proxyHost=IP -Dhttp.proxyPort=3128 -Dhttp.nonProxyHosts=localhost'

Tried all different types of variations:
- export JAVA_OPTS instead of just JAVA_OPTS=
- Adding these to the catalina_startup.sh or catalina.properties files
- Even tried Tomcat jProxyLoader http://jproxyloader.sourceforge.net/examples/web-application-on-tomcat.html

Still having no Joy. Please help! Really want to get this working

**Comment by scobal** [comment]
Could you try including your graphite server in the http.nonProxyHosts please?

**Comment by phateuk** [comment]
Graphite is running on the same server as seyren, hence the localhost entry in the -Dhttp.nonProxyHosts directive.

Makes no difference with it present or not. When it's removed, seyren can still talk to graphite so indicates it's completely ignoring the entire JAVA_OPTS list of params.
