### ISSUE TITLE
Is it possible to cut a new release?

### ISSUE THREAD

**Issue by Crim** [scobal/seyren#389]
Its been over a year since the last release was cut (Apr 14, 2015).  Is it possible to put together a more current release?

**Comment by scobal** [comment]
I've just released 1.4.0 here: https://github.com/scobal/seyren/releases/tag/1.4.0

Is there any chance you could check it out and let me know if you find any problems with it?

Thanks!

**Comment by alindeman** [comment]
@scobal Anything we should be aware of when upgrading? Should 1.3.0 cleanly migrate to 1.4.0? Are there any notable feature changes?

**Comment by scobal** [comment]
I haven't been involved much over the past year so it's hard for me to say I'm afraid.

**Comment by mrh666** [comment]
@scobal Any changelog? How to understand - is 1.4.0 back compatible or not?
