### ISSUE TITLE
Missing docs for "Consecutive Checks"?

### ISSUE THREAD

**Issue by boris317** [scobal/seyren#414]
I haven't been able to find any docs about the "Consecutive Checks" feature. How does it work? What is the relationship between "Consecutive Checks" and "Tolerance Level"?

**Comment by boris317** [comment]
Sorry - The reason I cannot find any docs is because the feature only exists in our fork of the code doh!

**Comment by rehevkor5** [comment]
@boris317 I took a look at the source code to see how it works and added a wiki page: https://github.com/ExpediaInc/seyren-1/wiki/Consecutive-Checks-&-Tolerance Better than nothing, I figure.
